# Generated by Django 2.2.7 on 2020-09-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='Apointment',
        ),
    ]
